#!/usr/bin/env bash

set -ex
set -o errexit
set -o nounset
set -o pipefail

IMAGES="${IMAGE_PREFIX}alertingest ${IMAGE_PREFIX}alertquery ${IMAGE_PREFIX}alertdist ${IMAGE_PREFIX}table-manager ${IMAGE_PREFIX}alertmanager"
IMAGE_TAG=$(./tools/image-tag)
QUAY_PREFIX=quay.io/
NO_QUAY=
BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
usage() {
    echo "$0 (-noquay)"
    exit 2
}

while [ $# -gt 0 ]; do
    case "$1" in
        "-noquay")
            NO_QUAY=true
            shift 1
            ;;
        *)
            usage
            exit 2
            ;;
    esac
done

push_image() {
    local image="$1"
    echo "Pushing ${image}:${IMAGE_TAG}"
    docker push ${image}:${IMAGE_TAG}

    if [ -n "${NO_QUAY}" ]; then
        return
    fi

    # remove the quey prefix and push to docker hub
    docker_hub_image=${image#$QUAY_PREFIX}
    # Push to openebs DockerHub repo when branch = staging
    if [[ "${BRANCH_NAME}" == "staging" ]]; then
            docker tag "${image}:${IMAGE_TAG}" "${docker_hub_image}:latest"
            docker push "${docker_hub_image}:latest"
    fi
    echo "Pushing ${docker_hub_image}:${IMAGE_TAG}"
    docker push ${docker_hub_image}:${IMAGE_TAG}
}

for image in ${IMAGES}; do
    if [[ "$image" == *"build"* ]]; then
        continue
    fi
    push_image "${image}" &
done

wait

