---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: alertdist
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: alertdist
    spec:
      containers:
      - name: alertdist
        image: mulebot/cortex-alertdist
        imagePullPolicy: Always 
        args:
        - -log.level=debug
        - -server.http-listen-port=80
        - -consul.hostname=172.17.0.2:8500
        - -distributor.replication-factor=1
        ports:
        - containerPort: 80
